---
title: "String Practice"
author: "Joaquin Sandoval"
date: "2025-08-19"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Practice with Strings 

```{r}

library(stringr) 
#copy data into rscript with tools, add ins, browse add ins, datapasta paste as dataframe 

library(lubridate)
alarm_report <- data.frame(
  stringsAsFactors = FALSE,
              date = c("2020-03-14", "2020-03-15", "2020-04-10", "2020-04-18"),
          building = c("Engineering-North",
                       "Bren Hall","Engineering-South","Engr-North"),
     alarm_message = c("10:02am -- HVAC system down, facilities management alerted",
                       "8:24am -- Elevator North out of service",
                       "12:41am -- Fire alarm, UCSB fire responded and cleared",
                       "9:58pm -- Campus point emergency siren, UCPD responded")
)

#1. replace 'Engr' with 'Engineering' in building column 
#2. separate building column into 'building' and 'wing'
#3. only retain rows in alarm_message column that has "responded"
#4. lubridate to correct date format

a <- alarm_report |> 
  mutate(building = str_replace(building, pattern = "Engr", replacement = "Engineering")) |> 
  separate(col = building, into = c("building", "wing"), sep = "-") |> 
  filter(str_detect(alarm_message, pattern = "responded")) |>
  mutate(date = lubridate::ymd(date))

```



